name: CI/CD Backend

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Escolha a ação Terraform a executar (apply ou destroy)"
        required: true
        default: "apply"
  push:
    branches: [main]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' || github.event_name != 'workflow_dispatch' }}
        run: terraform -chdir=terraform apply -auto-approve tfplan

      - name: Inject API URL into script.js
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          API_URL=$(terraform -chdir=terraform output -raw api_gateway_url | tr -d '\n\r')
          echo "Atualizando API_URL em script.js para: $API_URL/counter"
          sed -i "s|^const API_URL = .*|const API_URL = \"$API_URL/counter\";|" script.js

      - name: Terraform Destroy
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy' }}
        run: |
          echo "Executando Terraform destroy..."
          terraform -chdir=terraform destroy -auto-approve

      - name: Wait for API to be ready
        if: ${{ github.event.inputs.action == 'apply' || github.event_name != 'workflow_dispatch' }}
        run: sleep 30

      - name: Upload static files to S3
        if: ${{ (github.event.inputs.action == 'apply' || github.event_name != 'workflow_dispatch') && success() }}
        run: |
          aws s3 sync . s3://aws---cloud-resume-challenge-2025-bucket-s3 \
            --exclude "*" \
            --include "*.html" \
            --include "*.css" \
            --include "*.js" \
            --include "*.png" \
            --delete

      - name: Get CloudFront Distribution ID
        if: ${{ github.event.inputs.action == 'apply' && success() }}
        id: cf
        run: |
          cd terraform
          echo "DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV
          echo "CloudFront Distribution ID: $(terraform output -raw cloudfront_distribution_id)"

      - name: Invalidate CloudFront cache
        if: ${{ github.event.inputs.action == 'apply' && success() }}
        run: |
          echo "Invalidating CloudFront cache for distribution: $DISTRIBUTION_ID"
          aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"
