name: Terraform Destroy

on:
  workflow_dispatch:   # Executado manualmente pelo GitHub Actions

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Configura as credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Instala o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      # 4. Inicializa o Terraform
      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false

      # 5. Mostra o plano de destruição (para registro nos logs)
      - name: Terraform Plan Destroy
        run: terraform -chdir=terraform plan -destroy

      # 6. Executa o Destroy completo
      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -auto-approve
