name: CI/CD Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'script.js'
      - 'styles.css'
      - 'front.css'
      - 'assets/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Configura AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Pega outputs do Terraform (nome do bucket e id da distro)
      - name: Get Terraform outputs
        run: |
          cd terraform
          terraform init -backend=false
          echo "S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV
          echo "CF_DIST_ID=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

      # 4. Deploy arquivos pro S3
      - name: Sync files to S3
        run: aws s3 sync . s3://$S3_BUCKET_NAME --delete --exclude ".git/*" --exclude ".github/*" --exclude "terraform/*"

      # 5. Invalida cache do CloudFront
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CF_DIST_ID \
            --paths "/*"
